import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { motion, useInView } from "framer-motion";
import { ArrowLeft, ArrowRight, Package, Zap, CircleCheck as CheckCircle, Clock } from "lucide-react";
import { useRef } from "react";
import { useServiceStore } from "@/store/serviceStore";
import Card from "@/components/ui/Card";
import Button from "@/components/common/Button";
import Badge from "@/components/ui/Badge";
import Breadcrumb from "@/components/common/Breadcrumb";
export default function ServiceDetailsPage() {
    const { slug } = useParams();
    const { selectedService, fetchServiceBySlug, isLoading } = useServiceStore();
    const { services } = useServiceStore();
    useEffect(() => {
        if (slug) {
            fetchServiceBySlug(slug);
        }
    }, [slug, fetchServiceBySlug]);
    // Get related services (same category, excluding current service)
    const relatedServices = selectedService
        ? services
            .filter((s) => s.category === selectedService.category && s.id !== selectedService.id)
            .slice(0, 3)
        : [];
    // Animation refs
    const descRef = useRef(null);
    const materialsRef = useRef(null);
    const featuresRef = useRef(null);
    const ctaRef = useRef(null);
    const relatedRef = useRef(null);
    const descInView = useInView(descRef, { once: true, margin: "-100px" });
    const materialsInView = useInView(materialsRef, { once: true, margin: "-100px" });
    const featuresInView = useInView(featuresRef, { once: true, margin: "-100px" });
    const ctaInView = useInView(ctaRef, { once: true, margin: "-100px" });
    const relatedInView = useInView(relatedRef, { once: true, margin: "-100px" });
    if (isLoading) {
        return (_jsx("div", { className: "min-h-screen bg-gradient-to-b from-slate-50 to-white dark:from-slate-900 dark:to-slate-800 flex items-center justify-center", children: _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "animate-spin mb-4 flex justify-center", children: _jsx(Package, { className: "w-8 h-8 text-blue-600" }) }), _jsx("p", { className: "text-slate-600 dark:text-slate-400", children: "Loading service..." })] }) }));
    }
    if (!selectedService) {
        return (_jsx("div", { className: "min-h-screen bg-gradient-to-b from-slate-50 to-white dark:from-slate-900 dark:to-slate-800 flex items-center justify-center", children: _jsxs(Card, { className: "p-8 text-center max-w-sm", children: [_jsx("h2", { className: "text-2xl font-bold text-slate-900 dark:text-white mb-4", children: "Service Not Found" }), _jsx("p", { className: "text-slate-600 dark:text-slate-400 mb-6", children: "Sorry, we couldn't find the service you're looking for." }), _jsx(Link, { to: "/services", children: _jsx(Button, { children: "Back to Services" }) })] }) }));
    }
    return (_jsxs("div", { className: "min-h-screen bg-gradient-to-b from-slate-50 to-white dark:from-slate-900 dark:to-slate-800", children: [_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { duration: 0.5 }, className: "px-6 sm:px-8 py-6 border-b border-slate-200 dark:border-slate-700", children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsxs(Link, { to: "/services", className: "inline-flex items-center gap-2 text-slate-600 dark:text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 mb-4 transition-colors", children: [_jsx(ArrowLeft, { size: 18 }), "Back to Services"] }), _jsx(Breadcrumb, { items: [
                                { label: "Home", href: "/" },
                                { label: "Services", href: "/services" },
                                { label: selectedService.title },
                            ] })] }) }), _jsxs(motion.section, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { duration: 0.6 }, className: "relative h-96 md:h-[500px] overflow-hidden", children: [_jsx(motion.img, { src: selectedService.image, alt: selectedService.title, className: "w-full h-full object-cover", initial: { scale: 1.1 }, animate: { scale: 1 }, transition: { duration: 0.8 } }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/60 via-black/20 to-transparent" }), _jsx("div", { className: "absolute inset-0 flex items-end", children: _jsx("div", { className: "px-6 sm:px-8 pb-12 w-full max-w-6xl mx-auto", children: _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: 0.2 }, children: [selectedService.category && (_jsx(Badge, { variant: "primary", className: "mb-4", children: selectedService.category })), _jsx("h1", { className: "text-4xl md:text-5xl font-bold text-white mb-3", children: selectedService.title }), selectedService.basePrice && (_jsxs("p", { className: "text-lg text-blue-100 font-semibold", children: ["Starting from NPR ", selectedService.basePrice, "/sq.ft"] }))] }) }) })] }), _jsx(motion.section, { ref: descRef, initial: "hidden", animate: descInView ? "visible" : "hidden", variants: {
                    visible: { opacity: 1, y: 0 },
                    hidden: { opacity: 0, y: 20 },
                }, transition: { duration: 0.6 }, className: "px-6 sm:px-8 py-16 md:py-20", children: _jsxs("div", { className: "max-w-4xl mx-auto", children: [_jsx("h2", { className: "text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-6", children: "About This Service" }), _jsx("p", { className: "text-lg text-slate-600 dark:text-slate-400 leading-relaxed", children: selectedService.description }), _jsxs("div", { className: "mt-8 grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsxs("div", { className: "flex gap-4", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(CheckCircle, { className: "w-6 h-6 text-green-500" }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-slate-900 dark:text-white mb-1", children: "Premium Quality" }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-400", children: "Industry-leading materials and cutting-edge printing technology" })] })] }), _jsxs("div", { className: "flex gap-4", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(Clock, { className: "w-6 h-6 text-blue-500" }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-slate-900 dark:text-white mb-1", children: "Fast Turnaround" }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-400", children: "Quick production times without compromising on quality" })] })] }), _jsxs("div", { className: "flex gap-4", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(Zap, { className: "w-6 h-6 text-yellow-500" }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-slate-900 dark:text-white mb-1", children: "Expert Support" }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-400", children: "Professional guidance throughout your project journey" })] })] })] })] }) }), selectedService.materials && selectedService.materials.length > 0 && (_jsx(motion.section, { ref: materialsRef, initial: "hidden", animate: materialsInView ? "visible" : "hidden", variants: {
                    visible: { opacity: 1, y: 0 },
                    hidden: { opacity: 0, y: 20 },
                }, transition: { duration: 0.6 }, className: "px-6 sm:px-8 py-16 md:py-20 bg-slate-50 dark:bg-slate-800/50", children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsx("h2", { className: "text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-4", children: "Available Materials" }), _jsx("p", { className: "text-slate-600 dark:text-slate-400 mb-10 max-w-2xl", children: "We offer a variety of premium materials to suit your specific needs and budget requirements." }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: selectedService.materials.map((material, idx) => (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: materialsInView ? { opacity: 1, y: 0 } : { opacity: 0 }, transition: { duration: 0.5, delay: idx * 0.1 }, children: _jsx(Card, { className: "h-full p-6 dark:bg-slate-700 dark:border-slate-600 hover:shadow-xl transition-shadow", children: _jsxs("div", { className: "flex items-start gap-4", children: [_jsx("div", { className: "w-12 h-12 rounded-xl bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center flex-shrink-0", children: _jsx(Package, { className: "w-6 h-6 text-blue-600 dark:text-blue-400" }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-slate-900 dark:text-white mb-2", children: material }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-400", children: "Premium quality option for exceptional results" })] })] }) }) }, idx))) })] }) })), selectedService.features && selectedService.features.length > 0 && (_jsx(motion.section, { ref: featuresRef, initial: "hidden", animate: featuresInView ? "visible" : "hidden", variants: {
                    visible: { opacity: 1, y: 0 },
                    hidden: { opacity: 0, y: 20 },
                }, transition: { duration: 0.6 }, className: "px-6 sm:px-8 py-16 md:py-20", children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsx("h2", { className: "text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-4", children: "Key Features & Benefits" }), _jsx("p", { className: "text-slate-600 dark:text-slate-400 mb-10 max-w-2xl", children: "Discover what makes this service stand out and why our clients choose us for their printing needs." }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: selectedService.features.map((feature, idx) => (_jsxs(motion.div, { initial: { opacity: 0, x: -20 }, animate: featuresInView ? { opacity: 1, x: 0 } : { opacity: 0 }, transition: { duration: 0.5, delay: idx * 0.1 }, className: "flex gap-4 p-6 bg-slate-50 dark:bg-slate-800 rounded-2xl hover:shadow-lg transition-shadow", children: [_jsx("div", { className: "flex-shrink-0 mt-1", children: _jsx(CheckCircle, { className: "w-6 h-6 text-green-500" }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-slate-900 dark:text-white mb-1", children: feature }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-400", children: "Carefully crafted to meet the highest industry standards" })] })] }, idx))) })] }) })), _jsx(motion.section, { ref: ctaRef, initial: "hidden", animate: ctaInView ? "visible" : "hidden", variants: {
                    visible: { opacity: 1, y: 0 },
                    hidden: { opacity: 0, y: 20 },
                }, transition: { duration: 0.6 }, className: "px-6 sm:px-8 py-16 md:py-20 bg-slate-50 dark:bg-slate-800/50", children: _jsx("div", { className: "max-w-6xl mx-auto", children: _jsx(Card, { className: "bg-gradient-to-r from-blue-600 to-blue-500 border-0 text-white dark:from-blue-700 dark:to-blue-600 overflow-hidden", children: _jsxs("div", { className: "relative p-12 md:p-16", children: [_jsx("div", { className: "absolute inset-0 opacity-10", children: _jsx("div", { className: "absolute top-0 right-0 w-96 h-96 bg-white rounded-full blur-3xl" }) }), _jsxs("div", { className: "relative z-10 grid grid-cols-1 md:grid-cols-2 gap-8", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl md:text-4xl font-bold mb-4", children: "Ready to Get Started?" }), _jsxs("p", { className: "text-blue-50 text-lg mb-6", children: ["Get a personalized quote for your ", selectedService.title, " ", "project. Our team will work with you to understand your needs and deliver exceptional results."] })] }), _jsxs("div", { className: "flex flex-col justify-center gap-4", children: [_jsx(Link, { to: `/quote?serviceId=${selectedService.id}`, children: _jsxs(Button, { variant: "outline", size: "lg", className: "w-full bg-white text-blue-600 hover:bg-blue-50 font-semibold gap-2", children: ["Request Quote ", _jsx(ArrowRight, { size: 18 })] }) }), _jsx(Link, { to: "/contact", children: _jsx(Button, { variant: "outline", size: "lg", className: "w-full border-white text-white hover:bg-blue-400 font-semibold", children: "Contact Us" }) })] })] })] }) }) }) }), relatedServices.length > 0 && (_jsx(motion.section, { ref: relatedRef, initial: "hidden", animate: relatedInView ? "visible" : "hidden", variants: {
                    visible: { opacity: 1, y: 0 },
                    hidden: { opacity: 0, y: 20 },
                }, transition: { duration: 0.6 }, className: "px-6 sm:px-8 py-16 md:py-20", children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsx("h2", { className: "text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-4", children: "Related Services" }), _jsxs("p", { className: "text-slate-600 dark:text-slate-400 mb-10", children: ["Explore other services in the ", selectedService.category, " category"] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8", children: relatedServices.map((service, idx) => (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: relatedInView ? { opacity: 1, y: 0 } : { opacity: 0 }, transition: { duration: 0.5, delay: idx * 0.1 }, children: _jsx(Link, { to: `/services/${service.slug}`, children: _jsxs(Card, { className: "h-full overflow-hidden group dark:bg-slate-800 dark:border-slate-700 cursor-pointer", children: [_jsx("div", { className: "h-48 overflow-hidden bg-slate-200 dark:bg-slate-700", children: _jsx(motion.img, { src: service.image, alt: service.title, className: "w-full h-full object-cover", whileHover: { scale: 1.1 }, transition: { duration: 0.5 } }) }), _jsxs("div", { className: "p-6", children: [_jsx("h3", { className: "font-bold text-slate-900 dark:text-white mb-2 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors", children: service.title }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-400 line-clamp-2", children: service.description }), _jsxs("div", { className: "mt-4 flex items-center gap-2 text-blue-600 dark:text-blue-400 font-semibold", children: ["Learn More ", _jsx(ArrowRight, { size: 16 })] })] })] }) }) }, service.id))) })] }) }))] }));
}
