import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import { testimonials } from "@/data/testimonials";
import RatingStars from "@/components/testimonials/RatingStars";
import { ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";
export default function TestimonialsPreview() {
    const ref = useRef(null);
    const isInView = useInView(ref, { once: true, margin: "-100px" });
    return (_jsx("section", { ref: ref, className: "py-20 lg:py-28 bg-white dark:bg-slate-950", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 30 }, animate: isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }, transition: { duration: 0.6 }, className: "flex flex-col md:flex-row justify-between items-start md:items-end mb-12 gap-6", children: [_jsxs("div", { children: [_jsx("span", { className: "inline-block px-4 py-1.5 bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-sm font-semibold rounded-full mb-4", children: "Testimonials" }), _jsx("h2", { className: "text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-slate-900 dark:text-white mb-4", children: "What Our Clients Say" }), _jsx("p", { className: "text-lg text-slate-600 dark:text-slate-400 max-w-2xl", children: "Don't just take our word for it - hear from our satisfied customers" })] }), _jsxs(Link, { to: "/testimonials", className: "group inline-flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-2xl transition-all", children: ["View All", _jsx(ArrowRight, { className: "w-4 h-4 group-hover:translate-x-1 transition-transform" })] })] }), _jsx("div", { className: "grid md:grid-cols-2 lg:grid-cols-4 gap-8", children: testimonials.map((testimonial, idx) => (_jsxs(motion.div, { initial: { opacity: 0, y: 40 }, animate: isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 40 }, transition: { duration: 0.6, delay: idx * 0.15 }, whileHover: { y: -8 }, className: "bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-8 shadow-sm hover:shadow-xl transition-all", children: [_jsx(RatingStars, { rating: testimonial.rating }), _jsxs("p", { className: "text-slate-700 dark:text-slate-300 mt-5 mb-6 leading-relaxed italic", children: ["\"", testimonial.review, "\""] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "h-12 w-12 rounded-full bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-white font-bold text-lg", children: testimonial.avatar }), _jsxs("div", { children: [_jsx("h4", { className: "font-bold text-slate-900 dark:text-white", children: testimonial.customerName }), _jsx("p", { className: "text-sm text-slate-500 dark:text-slate-400", children: testimonial.company })] })] })] }, testimonial.id))) })] }) }));
}
